#!/bin/bash
clear
echo "Running containers"
docker ps;
echo ""
read -p 'Input container name to BKP: ' container
read -p 'Input database user: ' user
read -sp 'Input database password: ' pass
echo ""
puerto=$(docker ps --filter "name=$container" --format "table {{.Ports}}" | awk -F: '{print $2}' | awk -F- '{print $1}')

mysql -h localhost -P$(($puerto)) --protocol=tcp -u$user -p$pass -e "show databases"

read -p 'Input database name to Backup: ' datab
current_time=$(date "+%Y.%m.%d-%H.%M.%S")

docker exec $container /usr/bin/mysqldump -u $user --password=$pass $datab > $container.$datab.backup.$current_time.sql
